basic/myproject/core/urls.py
from django.conf.urls import include, url
from myproject.core import views as c

person_patterns = [
    url(r'^$', c.PersonList.as_view(), name='person_list'),
    url(r'^add/$', c.PersonCreate.as_view(), name='person_add'),
    url(r'^(?P<slug>[\w-]+)/$', c.person_detail, name='person_detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', c.person_update, name='person_edit'),
    url(r'^(?P<slug>[\w-]+)/delete/$', c.person_delete, name='person_delete'),
]

urlpatterns = [
    url(r'^$', c.home, name='home'),
    url(r'^person/', include(person_patterns)),
]

basic/myproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'', include('myproject.core.urls', namespace='core')),
    url(r'^admin/', admin.site.urls),
]

basic/myproject/core/models.py
from django.db import models
from django.core.urlresolvers import reverse_lazy
from localflavor.br.br_states import STATE_CHOICES
# List of values for use in choices
from .lists import GENDER_LIST, TREATMENT_LIST, PHONE_TYPE


class TimeStampedModel(models.Model):
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    modified = models.DateTimeField(auto_now_add=False, auto_now=True)

    class Meta:
        abstract = True


class Address(models.Model):
    address = models.CharField(max_length=100, blank=True)
    complement = models.CharField(max_length=100, blank=True)
    district = models.CharField(max_length=100, blank=True)
    city = models.CharField(max_length=100, blank=True)
    uf = models.CharField('UF', max_length=2,
                          choices=STATE_CHOICES, blank=True)
    cep = models.CharField('CEP', max_length=9, blank=True)

    class Meta:
        abstract = True


class Person(TimeStampedModel, Address):
    gender = models.CharField(max_length=1, choices=GENDER_LIST)
    treatment = models.CharField(
        max_length=4, choices=TREATMENT_LIST, default='')
    slug = models.SlugField('slug')
    first_name = models.CharField('first name', max_length=30)
    last_name = models.CharField('last name', max_length=30)
    cpf = models.CharField('CPF', max_length=11, unique=True, blank=True)
    birthday = models.DateTimeField(null=True, blank=True)
    email = models.EmailField(blank=True)
    blocked = models.BooleanField(default=False)

    class Meta:
        ordering = ['first_name']
        verbose_name = 'contact'
        verbose_name_plural = 'contacts'

    def __str__(self):
        fname = [self.get_treatment_display(), self.first_name, self.last_name]
        return ' '.join(filter(None, fname))

    full_name = property(__str__)

    def get_absolute_url(self):
        ''' return slug '''
        return reverse_lazy('core:person_detail', kwargs={'slug': self.slug})


class Phone(models.Model):
    phone = models.CharField(max_length=20, blank=True)
    person = models.ForeignKey('Person')
    phone_type = models.CharField(
        max_length=3, choices=PHONE_TYPE, default='pri')

    def __str__(self):
        return self.phone

basic/myproject/core/forms.py
from django import forms
from .models import Person

gender_list = [('M', 'male'), ('F', 'female')]


class PersonForm(forms.ModelForm):
    gender = forms.ChoiceField(
        choices=gender_list, initial='M', widget=forms.RadioSelect)

    class Meta:
        model = Person
        fields = ['gender', 'treatment', 'first_name', 'last_name', 'slug',
                  'email', 'cpf', 'address', 'complement', 'district', 'city',
                  'uf', 'cep', 'birthday', 'blocked']

    def clean_cpf(self):
        return self.cleaned_data['cpf'] or ''

basic/myproject/core/views.py
from django.core.urlresolvers import reverse_lazy as r
from django.db.models import Q
from django.shortcuts import render
from django.views.generic import CreateView, ListView, DetailView
from django.views.generic import UpdateView, DeleteView
from .models import Person
from .forms import PersonForm


def home(request):
    return render(request, 'index.html')


class CounterMixin(object):

    def get_context_data(self, **kwargs):
        context = super(CounterMixin, self).get_context_data(**kwargs)
        context['count'] = self.get_queryset().count()
        return context


class PersonList(CounterMixin, ListView):
    template_name = 'core/person_list.html'
    model = Person
    context_object_name = 'persons'
    paginate_by = 10

    def get_queryset(self):
        persons = Person.objects.all()
        q = self.request.GET.get('search_box')
        if q is not None:
            persons = persons.filter(
                Q(first_name__icontains=q) |
                Q(last_name__icontains=q))
        return persons


class PersonCreate(CreateView):
    template_name = 'core/person_form.html'
    form_class = PersonForm
    success_url = r('core:person_list')


person_detail = DetailView.as_view(model=Person)

person_update = UpdateView.as_view(model=Person, form_class=PersonForm)

person_delete = DeleteView.as_view(model=Person,
                                   success_url=r('core:person_list'))

basic/myproject/core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="https://www.djangoproject.com/favicon.ico">

    <title>{% block title %}Django{% endblock title %}</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- Font Awesome core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- My CSS -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/social.css' %}">
    <!-- JQuery -->
    <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
    <!-- Bootstrap core JS -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <style type="text/css">
      /* Move down content because we have a fixed navbar that is 60px tall */
      body {
        padding-top: 50px;
      }
    </style>

  </head>
  <body>

  {% include "nav.html" %}

  <div id="wrap">
    <div class="container">
      {% block content %}{% endblock content %}
    </div>
  </div>

  {% include "footer.html" %}

  </body>
</html>

basic/myproject/core/templates/core/person_detail.html
{% extends "base.html" %}

{% load static %}

{% block title %}Person Detail{% endblock title %}

{% block content %}

<ul class="breadcrumb">
  <li><a href="{% url 'core:home' %}">Home</a> <span class="divider"></span></li>
  <li><a href="{% url 'core:person_list' %}">Contacts</a> <span class="divider"></span></li>
  <li class="active">{{ object.full_name }}</li>
</ul>

<div class="col-lg-8">
  <div class="col-md-2 column">
    <img src="https://cdn4.iconfinder.com/data/icons/ionicons/512/icon-person-128.png" class="img-square" style="height: 100px;" />
  </div>
  <div class="col-md-offset-3 column">
    <h1>{{ object.full_name }}</h1>
    {% if object.email %}
      <h4><span class="glyphicon glyphicon-envelope"></span><a href="#"> {{ object.email }}</a></h4>
    {% endif %}
    <div class="social">
      <ul>
        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
        <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
        <li><a href="#"><i class="fa fa-github"></i></a></li>
        <li><a href="#"><i class="fa fa-pinterest"></i></a></li>
        <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
        <li><a href="#"><i class="fa fa-instagram"></i></a></li>
        <li><a href="#"><i class="fa fa-skype"></i></a></li>
        <li><a href="#"><i class="fa fa-telegram"></i></a></li>
        <li><a href="#"><i class="fa fa-slack"></i></a></li>
      </ul>
    </div>
  </div>

  </br>

  <table class="table table-user-information">
    <tbody>
      {% if object.phone_set.all %}
        {% for phone in object.phone_set.all %}
          <tr>
            <th class="col-md-3 text-right"><span class="glyphicon glyphicon-earphone"></span></th>
            <td>{{ phone.phone }} <i class="fa fa-whatsapp ok"></i> {{ phone.get_phone_type_display }}</td>
          </tr>
        {% endfor %}
      {% else %}
        <tr>
          <th class="col-md-3 text-right"><span class="glyphicon glyphicon-earphone"></span></th>
          <td>---</td>
        </tr>
      {% endif %}

      {% if object.address %}
        <tr>
          <th class="col-md-3 text-right"><span class="glyphicon glyphicon-map-marker"></span></th>
          <td>{{ object.address }}
            {% if object.complement %} - {{ object.complement }}{% endif %}
            {% if object.district %} - {{ object.district }}{% endif %}
          </td>
        </tr>
        <tr>
          <th class="col-md-3 text-right"></th>
          <td>
            {% if object.city %}{{ object.city }}{% endif %}
            {% if object.uf %} - {{ object.uf }}{% endif %}
            {% if object.cep %} - {{ object.cep }}{% endif %}
          </td>
        </tr>
      {% endif %}
      {% if object.cpf %}
        <tr>
          <th class="col-md-3 text-right">CPF</th>
          <td>{{ object.cpf }}</td>
        </tr>
      {% endif %}
      {% if object.birthday %}
        <tr>
          <th class="col-md-3 text-right">Birthday</th>
          <td>{{ object.birthday|date:"d/m/Y" }}</td>
        </tr>
      {% endif %}
      <tr>
        <th class="col-md-3 text-right">Blocked</th>
          <td><span class="glyphicon {{ object.blocked|yesno:'glyphicon-ok-sign ok,glyphicon-minus-sign no'}}"></span></td>
      </tr>

    </tbody>
  </table>
  <!-- edit -->
  <a href="{% url 'core:person_edit' person.slug %}">
      <button id="edit_person" type="button" class="btn btn-success">
          <span class="fa fa-pencil"></span> Edit
      </button>
  </a>
  <!-- delete with modal -->
  <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#myModal">
      <span class="fa fa-times"></span> Exclude
  </button>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Confirm</h4>
      </div>
        <form action="{% url 'core:person_delete' person.slug %}" method="POST">
      <div class="modal-body">
          {% csrf_token %}
          You want delete "{{ object }}"?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        <input type="submit" class="btn btn-danger" value="Deletar" />
      </div>
        </form>
    </div>
  </div>
</div>

{% endblock content %}

basic/myproject/core/templates/core/person_form.html
{% extends "base.html" %}

{% load bootstrap %}

{% block title %}Person Form{% endblock title %}

{% block content %}

<form class="form-horizontal col-sm-6" action="." method="POST">
  <legend>Add Contact</legend>
  {% csrf_token %}
  {{ form|bootstrap_horizontal }}

  <div class="form-group">
    <div class="col-sm-10 col-sm-offset-2">
      <button type="submit" id="id_submit" class="btn btn-primary">Save</button>
    </div>
  </div>
</form>

{% endblock content %}

basic/myproject/core/templates/core/person_list.html
{% extends "base.html" %}

{% block title %}Contacts{% endblock title %}

{% block content %}

<form class="navbar-form navbar-right" action="." method="get">
  <!-- add -->
  <a href="{% url 'core:person_add' %}">
    <button type="button" class="btn btn-primary">
      <span class="glyphicon glyphicon-plus"></span> Add
    </button>
  </a>
  <!-- search form -->
  <div class="form-group">
    <input id="search_box" name="search_box" type="text" placeholder="Search..." class="form-control">
    <button type="submit" class="btn btn-success form-control"><span class="glyphicon glyphicon-search"></span></button>
  </div>
</form>

<h2>Contacts List</h2>

{% if persons %}
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th>CPF</th>
        <th>Birthday</th>
        <th class="text-center">Blocked</th>
      </tr>
    </thead>
    <tbody>
    {% for person in persons %}
      {% if person.blocked %}
        <tr class="danger">
      {% else %}
        <tr>
      {% endif %}
        <td><a href="{{ person.get_absolute_url }}">{{ person.full_name }}</a></td>
        <td>{{ person.email }}</td>
        {% if person.phone_set.first %}
          <td>{{ person.phone_set.first }} 
          {% if person.phone_set.count > 1 %}
            <a href="{{ person.get_absolute_url }}">+{{ person.phone_set.count|add:"-1" }}</a>
          {% endif %}
          </td>
        {% else %}
          <td>---</td>
        {% endif %}
        <td>{{ person.cpf }}</td>
        <td>{{ person.birthday|date:"d/m/Y" }}</td>
        {% if person.blocked %}
          <td class="text-center"><span class="glyphicon glyphicon-ok-sign" style="color: #44AD41"></span></td>
        {% else %}
          <td class="text-center"><span class="glyphicon glyphicon-minus-sign" style="color: #DE2121"></span></td>
        {% endif %}
      </tr>
    {% endfor %}
    </tbody>
  </table>
{% else %}
  <div class="alert alert-warning text-center">
    <p>Without items in this list.</p>
    <!-- add -->
    <a href="{% url 'core:person_add' %}">
      <button type="button" class="btn btn-primary">
        <span class="glyphicon glyphicon-plus"></span> Add
      </button>
    </a>
  </div>
{% endif %}

<div>
  {% if count > 0 %}
    <hr>
    <h3>{{ persons|length }} contact{{ persons|length|pluralize }}</h3>
    <h4><b>Total:</b> {{ page_obj.paginator.count }} contact{{ page_obj.paginator.count|pluralize }}</h4>
  {% endif %}
</div>

<!-- pagination -->
{% if count > 0 %}
  {% include "pagination.html" %}
{% endif %}

{% endblock content %}

basic/myproject/core/templates/footer.html
<div id="footer">
  <div class="container">
    <p class="credit pull-left">Example by <a href="https://github.com/rg3915/">Régis da Silva</a> &copy; 2017 &middot; <a href="">download</a></p>
    <div class="socialfooter pull-center">
      <ul>
        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
        <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
        <li><a href="#"><i class="fa fa-github"></i></a></li>
        <li><a href="#"><i class="fa fa-pinterest"></i></a></li>
        <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
        <li><a href="#"><i class="fa fa-instagram"></i></a></li>
        <li><a href="#"><i class="fa fa-skype"></i></a></li>
        <li><a href="#"><i class="fa fa-telegram"></i></a></li>
        <li><a href="#"><i class="fa fa-slack"></i></a></li>
      </ul>
    </div>
  </div>
</div>

basic/myproject/core/templates/index.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <div class="jumbotron">
            <h1>Welcome!</h1>
            <h3>Contacts list make in Django.</h3>
            <p>The project contains:</p>
            <ul>
            <li>Core App</li>
            <li>Person Model</li>
            <li>Person List</li>
            <li>Person Detail</li>
            <li>Person Form</li>
            <li>Person Admin</li>
            <li>Tests with Selenium</li>
            <li>Fixtures with Generate Random Values</li>
            </ul>
            <a href="{% url 'core:person_add' %}">
              <button id="new_customer" type="button" class="btn btn-primary">
                <span class="glyphicon glyphicon-plus"></span> Register
              </button>
            </a>
        </div>
    </div>
{% endblock content %}

basic/myproject/core/templates/nav.html
<!-- Menu -->
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="current"><a href="{% url 'core:home' %}"><span class="glyphicon glyphicon-home"></span> Home</a></li>
        <li><a href="{% url 'core:person_list' %}"><span class="fa fa-users"></span> Contacts</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'admin:index' %}">Admin</a></li>
      </ul>
    </div>
  </div>
</div>

basic/myproject/core/templates/pagination.html
<!-- pagination -->
<div class="row text-center">
    <div class="col-lg-12">
        <ul class="pagination">
            <li><a href="?page=1"><span>&laquo;</span></a></li>
            {% if page_obj.has_previous %}
                <li><a href="?page={{ page_obj.previous_page_number }}">&lsaquo;</a></li>
            {% endif %}
            <li><a href="?page={{ page_obj.number }}">{{ page_obj.number }}</a></li>
            <!-- { for pg in page_obj.paginator.page_range %}
                { if page_obj.number == pg %}
                    <li class="active"><a href="?page={{ pg }}">{{ pg }}</a></li>
                { else %}
                    <li><a href="?page={{ pg }}">{{ pg }}</a></li>
                { endif %}
            { endfor %} -->
            {% if page_obj.has_next %}
                <li><a href="?page={{ page_obj.next_page_number }}">&rsaquo;</a></li>
            {% endif %}
            <li><a href="?page={{ page_obj.paginator.num_pages }}"><span>&raquo;</span></a></li>
        </ul>
    </div>
</div>